### ISSUE TITLE
looks good -- minor suggestion

### ISSUE THREAD

**Issue by JeffreySarnoff** [zot/DifferenceLists.jl#1]
You could `import Base: push!, pushfirst!` and name your corresponding routines with the trailing `!`, which, by convention indicates alter-in-place or replace-with-altered.

**Comment by zot** [comment]
Thanks!

The structure is supposed to be immutable, so that it's safe to reuse parts. I suppose I could make a mutable version as well...

**Comment by zot** [comment]
I changed push() and pushfirst() to use same the argument order as push!() and pushfirst!()

**Comment by JeffreySarnoff** [comment]
that is a good call
